### ISSUE TITLE
Error opening files in DataHub

### ISSUE THREAD

**Issue by dawsonv** [berkeley-dsep-infra/hubs#6941]
### Bug description

A student in Econ148 (ammo) is having trouble opening files in our DataHub. After clicking this [notebook link](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FUCB-Econ-148%2Fecon148-sp25&branch=main&urlpath=lab%2Ftree%2Fecon148-sp25%2Flab%2Flab08%2Flab08.ipynb), they encounter this error:

![Image](https://github.com/user-attachments/assets/7c453255-a3d6-4dd1-906c-77d413ae4798)

They also don't seem to have access to most other course files in the `econ148-sp25` directory. I'm able to reproduce the error by opening their DataHub from the admin panel, but can't find a solution. Any help would be greatly appreciated. 

### Environment & setup

- Hub: datahub / econ148-sp25
- Language: Python

### How to reproduce

From the admin console, select the user ammo and click Access Server. Select the folder `econ148-sp25` (and note that the contents of the folder are mostly missing). Open the console and running `git status`. This should yield the following:

```
jovyan@jupyter-ammo:~/econ148-sp25$ git status
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by balajialg** [comment]
@dawsonv The error seems to stem from an incomplete clone of the econ148 repository. I've addressed this by renaming the user's existing directory to `econ148_sp25_1` (it only had an empty 'lab8' folder) and then re-cloning the econ148 repository using the link you shared. The new repository, located in the user's home directory, now contains all their content. Please refer to the snapshots below for more information! Let me know if this fixes the issue for the user?

**Old repo (which is empty):**
![Image](https://github.com/user-attachments/assets/07916fee-fb08-4340-96b1-f92809846da9)

**Newly cloned repo:**
![Image](https://github.com/user-attachments/assets/429628f1-e5d5-4b0e-ad70-87c7e6b32c12)

**Comment by amandamo** [comment]
Hello, this is Amanda.

The problem still has not been fixed unfortunately. It now shows a blank page with "service unavailable" when I try to open the lab.

<img width="1267" alt="Image" src="https://github.com/user-attachments/assets/bafd76b4-a37d-43b4-a04f-7b089489d25c" />

**Comment by amandamo** [comment]
Hello, this is Amanda. 

I think the problem has been fixed. My lab is opening up properly. Thank you very much!
